spring:
  mvc:
    view:
      prefix: /JSP/
      suffix: .jsp
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/gpsdb?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      stat-view-servlet:
#        login-username: admin
#        login-password: admin
  datasource:
    url: jdbc:mysql://121.36.46.123:3306/gpsDB?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 789po.posdou12.QVM
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      stat-view-servlet:
        login-username: admin
        login-password: admin




mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: com/chy/mybatis/mappers/*.xml
  type-aliases-package: com.data.entity
server:
  port: 8080
  servlet:
    context-path: /web
